name: testmodels

on:
  push:
    branches:
      - main

jobs:
  project4_network:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install Django
        run: pip install --user django

      - name: Run Django unit tests
        run: |
          cd project4 
          python manage.py test
